version: '3.1'

volumes:
  db_storage:
  n8n_storage:

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: cslab1benov
    volumes:
      - ./cities.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nocodb:
    image: nocodb/nocodb:latest
    ports:
      - 80:8080
    environment:
      NC_DB: pg://db:5432?u=postgres&p=cslab1benov&d=nocodb
    depends_on:
      - db

  
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=cslab1benov
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
    command: /bin/sh -c "n8n start --tunnel"
    depends_on:
      - db
      - nocodb
    
  smtp:
    image: rnwood/smtp4dev:v3
    ports:
      - 2525:25
      - 3000:80