version: '3.1'

volumes:
  db_storage:
  n8n_storage:

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: cslab1benov
    volumes:
      - ./cities.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nocodb:
    image: nocodb/nocodb:latest
    ports:
      - 80:8080
    environment:
      NC_DB: pg://db:5432?u=postgres&p=cslab1benov&d=nocodb
    depends_on:
      - db

  